### ISSUE TITLE
Update to `adyenAdyen/adyen-web` `v5.27.0` for Swish payment method always triggers an error on mobile

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-adyen#14]
- https://github.com/Adyen/adyen-web/issues/1712
- https://github.com/Adyen/adyen-web/releases/tag/v5.27.0

> On mobile, redirecting the shopper to another app no longer triggers the `onError` callback with an `AdyenCheckoutError`. https://github.com/Adyen/adyen-web/pull/1764

**Comment by rvdsteege** [comment]
I was going to update, but it seems the new scripts/styles are not yet available.

HTTP `404` → https://checkoutshopper-test.adyen.com/checkoutshopper/sdk/5.27.0/adyen.js

<img width="1004" alt="Scherm­afbeelding 2022-10-05 om 17 02 39" src="https://user-images.githubusercontent.com/10371164/194094554-83f29539-cae4-43df-b644-b50092f94da5.png">

**Comment by remcotolsma** [comment]
Should/can we switch to `npm` as this is recommended?
