### ISSUE TITLE
Plugin Dependencies problem "Pronamic Pay" or "Pronamic Pay Premium"

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-adyen#25]
> @remcotolsma this prevents the plugin from being activated with https://github.com/pronamic/pronamic-pay-premium, is that correct?
> 
> <img alt="Scherm­afbeelding 2024-05-15 om 16 59 01" width="1174" src="https://private-user-images.githubusercontent.com/10371164/330856504-137de3a2-e799-442b-8291-365722bea761.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTM5MzEsIm5iZiI6MTcxNTg1MzYzMSwicGF0aCI6Ii8xMDM3MTE2NC8zMzA4NTY1MDQtMTM3ZGUzYTItZTc5OS00NDJiLTgyOTEtMzY1NzIyYmVhNzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwMDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZGMzMDljYmFiM2VhMDcxYjVhZTlmODAwYjgxMTIyYjdhZGQ1NDRjZTAxNjk4NzhhZjg4ZjkzNTY1ZGY5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cICX07wKJkDQfsa1ED8exOkIUz7dEKjO2ybp8eontBg">

_Originally posted by @rvdsteege in https://github.com/pronamic/wp-pronamic-pay-adyen/commit/b8b2fd05efca0f1685fca3e1b7e89bd0b8cab71a#commitcomment-142048382_

Currently this plugin requires https://wordpress.org/plugins/pronamic-ideal/, but this add-on also works fine with the Pronamic Pay Premium plugin.

The "Requires Plugins" header is limited, we cannot use 'or' conditions.
https://make.wordpress.org/core/2024/03/15/wordpress-6-5-field-guide/

Shall we remove this header?

https://github.com/pronamic/wp-pronamic-pay-adyen/blob/839b42e58d4d3a676703b0a28b14a583ccce0766/pronamic-pay-adyen.php#L19

**Comment by rvdsteege** [comment]
Seems there is a filter for this specific case:

> The `wp_plugin_dependencies_slug` filter hook has been introduced to allow for alterations to dependency slugs. For example, if a dependent plugin declares `my-plugin` as a dependency, and a premium version of `my-plugin` exists, the premium version can filter the slug and convert it to `my-plugin-pro` so that it can be detected by Plugin Dependencies.

https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/

**Comment by remcotolsma** [comment]
Improved in https://github.com/pronamic/pronamic-pay-premium/commit/bbbad6d0771f320087f47acfd03f05adb47a4a68.

<img width="1360" alt="Scherm­afbeelding 2024-05-16 om 12 27 42" src="https://github.com/pronamic/wp-pronamic-pay-adyen/assets/869674/6ba6ae8e-db29-4400-bce2-7316deddd01f">
